### ISSUE TITLE
Error with Mock module in Maltego

### ISSUE THREAD

**Issue by dom-newman** [soxoj/maigret-maltego#1]
Hi, I am still getting error in debug console of Maltego:
Double checked of installing mock. Thank you

`Traceback (most recent call last):
  File "project.py", line 2, in <module>
    import transforms
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/maigret-maltego/transforms/__init__.py", line 1, in <module>
    from .Maigret import Maigret
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/maigret-maltego/transforms/Maigret.py", line 3, in <module>
    from mock import Mock
ModuleNotFoundError: No module named 'mock'`

**Comment by soxoj** [comment]
Hey! I've tried to make a fix, please check [this updated version of script](https://github.com/soxoj/maigret-maltego/tree/mock-import-error-fix)
